# HÆ¯á»šNG DáºªN CÃ€I Äáº¶T WEBHOOK SEPAY.VN:
# 1. Táº¡i cáº¥u hÃ¬nh Webhook trÃªn Sepay.vn, má»¥c "Kiá»ƒu chá»©ng thá»±c" hÃ£y chá»n: "API Key"
# 2. DÃ¡n API Key tá»« bÃªn dÆ°á»›i vÃ o má»¥c "API Key" trÃªn Sepay.vn
# 3. "URL gá»i Ä‘áº¿n" Ä‘iá»n: http://<IP_VPS_CUA_BAN>:30079
# 4. "Request Content type" chá»n: application/json

ğŸ’ TÃ€I TRá»¢ HOSTING: https://cloudcheap.asia/
ğŸ’¬ DISCORD SUPPORT: https://discord.gg/k99aC2mYJj

sepay:
  account_number: "0903982264"
  bank_code: "MB"
  account_name: "PHAN QUOC AN"
  
  # Báº¡n tá»± Ä‘áº·t API Key nÃ y (VÃ­ dá»¥: abc123xyz...)
  # Sau Ä‘Ã³ dÃ¡n chÃ­nh xÃ¡c vÃ o má»¥c "API Key" trong "Cáº¥u hÃ¬nh chá»©ng thá»±c WebHooks" trÃªn Sepay.vn
  api_key: ""
  
  # Port nÃ y pháº£i khá»›p vá»›i URL gá»i Ä‘áº¿n (VD: 30079)
  webhook_port: 30079

  # Khuyáº¿n mÃ£i
promotion:
  enabled: false
  bonus_percent: 20
  # MÃºi giá» server: Asia/Ho_Chi_Minh (Cá»‘ Ä‘á»‹nh, khÃ´ng cáº§n chá»‰nh)
  
  # Check promotion status based on end_date
  # Format: "dd/MM/yyyy HH:mm" (VÃ­ dá»¥: 30/04/2025 23:59)
  # Náº¿u Ä‘á»ƒ trá»‘ng "" -> Khuyáº¿n mÃ£i cháº¡y vÃ´ thá»i háº¡n (khi enabled: true)
  end_date: ""

  messages:
    gui_title: "&eâš¡ ÄANG KHUYáº¾N MÃƒI"
    gui_lore:
      - "&7Há»‡ thá»‘ng Ä‘ang táº·ng thÃªm &6%bonus%%"
      - "&7cho má»i giao dá»‹ch!"
    chat_header: "&eâš¡ &lKHUYáº¾N MÃƒI ÄANG DIá»„N RA!"
    chat_desc: "&fNáº¡p ngay Ä‘á»ƒ nháº­n thÃªm &6+%bonus%% &fgiÃ¡ trá»‹."
    bonus_received: "&eâš¡ &lKHUYáº¾N MÃƒI: &fBáº¡n Ä‘Æ°á»£c táº·ng thÃªm &6%bonus%% &fgiÃ¡ trá»‹ náº¡p!"

database:
  type: "sqlite"
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""

discord:
  webhook_url: ""
  title: "â­ Giao dá»‹ch thÃ nh cÃ´ng!"
  color: "#00FF00"
  footer: "Sepay Payment System"

transaction:
  content_prefix: "NAP "
  
  # Máº·c Ä‘á»‹nh: 10,000Ä‘ = 10 Points
  exchange_rate: 0.001

effects:
  title:
    enabled: true
    title: "&a&lNáº P THáºº THÃ€NH CÃ”NG"
    subtitle: "&eBáº¡n Ä‘Ã£ nháº­n Ä‘Æ°á»£c &f%game_money% Points"
    fade_in: 10
    stay: 70
    fade_out: 20
  firework:
    enabled: true
    power: 1
    type: "BALL_LARGE"
    colors:
      - "RED"
      - "YELLOW"
      - "GREEN"

actions:
  on_success:
    - "points give %player% %game_money%"
    - "broadcast &8[&aSepay&8] &bNgÆ°á»i chÆ¡i &f%player% &bvá»«a á»§ng há»™ &f%,0f VNÄ&b. Cáº£m Æ¡n Ä‘áº¡i gia!"

messages:
  prefix: "&8[&aSepay&8] &r"
  only_player: "&cLá»‡nh nÃ y chá»‰ dÃ nh cho ngÆ°á»i chÆ¡i!"
  invalid_amount: "&cSá»‘ tiá»n khÃ´ng há»£p lá»‡! Vui lÃ²ng náº¡p tá»‘i thiá»ƒu 1,000 VNÄ."
  generating_qr: "&eÄang khá»Ÿi táº¡o mÃ£ QR... Äá»«ng Ä‘Ã³ng tÃºi Ä‘á»“ nhÃ©!"
  map_given: "&aMÃ£ QR Ä‘Ã£ sáºµn sÃ ng! Báº¡n hÃ£y cáº§m báº£n Ä‘á»“ vÃ  quÃ©t Ä‘á»ƒ thanh toÃ¡n."
  inventory_full: "&cTÃºi Ä‘á»“ cá»§a báº¡n Ä‘Ã£ Ä‘áº§y, khÃ´ng thá»ƒ nháº­n báº£n Ä‘á»“ QR."
  success: "&aCáº£m Æ¡n báº¡n Ä‘Ã£ á»§ng há»™ mÃ¡y chá»§!"
